### ISSUE TITLE
Positively buoyant vehicle behavior on surface 

### ISSUE THREAD

**Issue by braanan** [osrf/lrauv#167] opened 2022-03-10 22:42 UTC
Hi @arjo129, 

Seeing some odd behavior when spawning the vehicle on the surface with no mission running. Seems like the buoyancy surface forces are translating to forward thrust. Not sure if  #166 is targeting this issue.

https://user-images.githubusercontent.com/7927479/157767001-d2573cab-3ced-402c-9696-9eb48cebe79c.mp4

I confirmed the vehicle thruster is off.

**Comment by arjo129** [comment] 2022-03-11 03:33
No #166 will not solve this behavior. The behavior is caused by complex interactions between the oscillation on the surface and the hydrodynamics plugin. The issue is the added mass sign is in the wrong direction resulting in a reinforcement of oscillations. This is resolved by #59.

**Closed** 2022-03-16 16:16 UTC
